### ISSUE TITLE
Add Support for Thunderbird 91.0

### ISSUE THREAD

**Issue by jaisekjames** [opto/Expression-Search-NG#17] opened 2021-08-12 05:17 UTC
Expression search NG is not working with thunderbird 91.0.

Pls add support for thunderbird 91.0.

**Comment by opto** [comment] 2021-08-12 09:34
this is underway.
The search box is working already, but the settings dialog is messed up because Thunderbird deprecated the grid and other visual components.

**Comment by koobs** [comment] 2021-08-15 03:12
Dupe of #10

**Comment by jaisekjames** [comment] 2021-09-07 08:49
> 
> 
> this is underway.
> The search box is working already, but the settings dialog is messed up because Thunderbird deprecated the grid and other visual components.

If you able to add tab like this, size may reduce.
![tabs](https://user-images.githubusercontent.com/44542605/132314915-6d3d2001-c02b-4293-b913-43957991099d.png)

**Closed as completed** 2021-10-26 12:45 UTC
